### ISSUE TITLE
todo 1

### ISSUE THREAD

**Issue by PavelPZ** [PavelPZ/wikib#1]
- [x] download db during seed
- [x] debugDeviceId to hive DB name
- [x] tests for changing devices
- [x] changing logged => unlogged (compare hive DB size for deciding if use local on cloud DB as a master)
- [ ] global internet connection provider
- [ ] flutter login for windows
